# Generated by Django 4.2 on 2023-04-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noDpi', models.IntegerField(verbose_name='Numero de DPI')),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('lugar_nac', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emision de DPI')),
                ('fecha_venc', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'DPi',
                'verbose_name_plural': 'DPIS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('snombre', models.CharField(max_length=100, verbose_name='Segundo Nombre')),
                ('papellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('sapellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('nit', models.CharField(max_length=15, verbose_name='Numero de Nit')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion Actual')),
                ('aldea', models.CharField(max_length=50, verbose_name='Aldea')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('Departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(verbose_name='Numero de telefono')),
                ('religion', models.CharField(choices=[('Niguno', 'Ninguno'), ('Catalogo', 'Catolico'), ('Evangelico', 'Evangelico'), ('Mornon', 'Mormon'), ('Ateo', 'Ateo')], max_length=11, verbose_name='Religion')),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_persona.dpi', verbose_name='Numero de DPI')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
    ]
