# Generated by Django 4.2 on 2023-04-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
